name: Liang61_Iron_Action

on:
  schedule:
    - cron: '45 1 * * 1-5' # 09:45
    - cron: '15 2 * * 1-5' # 10:15
    - cron: '0 6 * * 1-5'  # 14:00
    - cron: '45 6 * * 1-5' # 14:45
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run_strategy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Deps
        run: pip install akshare pandas requests
      - name: Scan
        run: python main.py
      - name: Deploy to Web
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
