name: Liang61_Auto
on:
  schedule:
    - cron: '45 1 * * 1-5'
    - cron: '15 2 * * 1-5'
    - cron: '0 6 * * 1-5'
    - cron: '45 6 * * 1-5'
  workflow_dispatch:

# 添加以下这三行，强制赋予权限
permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Engine
        run: |
          pip install -r requirements.txt
          python main.py
      - name: Deploy Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages  # 强制发布到此分支
